refucktored cp-p
- removed unnecessary options: -F, --new-line, --lf-paste
- rewritten command line parsing to avoid quirks due to changing IFS
- fixed handling of the '--' option separator
- stored calculated sizes of all sources in an associative array to
  avoid useless re-calculating after the copy/move
- simplified the code for handling the names of existing files, changed
  to the default 'lf' format (i.e. "$fname.~$copy_n~")
- changed default options for 'cp': --archive --reflink=auto
- added the copy_file_range system call to the strace command to show
  the progress correctly on newer coreutils (see
  https://github.com/Naheel-Azawy/cp-p/issues/4 for details)
- parsing the strace output via process redirection to keep the original
  stdout and stderr of the straced command

diff --git a/cp-p b/cp-p
--- a/cp-p
+++ b/cp-p
@@ -1,6 +1,94 @@
-#!/bin/sh
-# Based on https://github.com/ericpaulbishop/cp_p
+#!/bin/bash
+
+# Based on https://github.com/Naheel-Azawy/cp-p
+# which is based on https://github.com/ericpaulbishop/cp_p
 # and https://unix.stackexchange.com/questions/44040/a-standard-tool-to-convert-a-byte-count-into-human-kib-mib-etc-like-du-ls1
+
+# set some shell options
+set -o errexit
+set -o nounset
+set -o noglob
+set -o pipefail
+
+# check if output is a tty
+if [ -t 1 ]; then
+    R=''
+    B='\033[0E\033[K'
+    W=$(tput cols)
+else
+    R='\n'
+    B=''
+    W=99999999
+fi
+
+help_opt=0
+end_of_opts=0
+cmd="cp"
+opts=""
+srcs=()
+dest=""
+
+print_help()
+{
+    cat >&2 << EOF
+Usage: $cmd-p [OPTION]... SOURCE DEST
+Like $cmd but with progress information.
+
+Check '$cmd --help' for the options.
+EOF
+    exit 1
+}
+
+parse_command_line()
+{
+    last=""
+    while [ $# -gt 0 ]; do
+        arg="$1"
+        shift
+        if [ $end_of_opts -eq 0 ]; then
+            case "$arg" in
+                -t | --target-directory)
+                    if [ $# -gt 0 ]; then
+                        dest=$1
+                        shift
+                        continue
+                    else
+                        echo "$cmd: option requires an argument -- '$arg'" >&2
+                        echo "Try '$cmd --help' for more information." >&2
+                        exit 1
+                    fi
+                    ;;
+                --target-directory=*)
+                    dest="${arg#*=}"
+                    if [[ "$dest" = "" ]]; then
+                        echo "$cmd: option requires an argument -- '--target-directory'" >&2
+                        echo "Try '$cmd --help' for more information." >&2
+                        exit 1
+                    fi
+                    continue
+                    ;;
+                --mv) cmd="mv"; continue ;;
+                --help) help_opt=1; continue ;;
+                --) end_of_opts=1; continue ;;
+                -*) opts="$opts $arg"; continue ;;
+            esac
+        fi
+        if [[ -n "$last" ]]; then
+            srcs+=("$last")
+        fi
+        last="$arg"
+    done
+
+    if [ -z "$dest" ]; then
+        dest="$last"
+    else
+        srcs+=("$last")
+    fi
+
+    if [[ "$help_opt" = 1 ]] || [[ "${srcs[@]}" = "" ]] || [[ "$dest" = "" ]]; then
+        print_help
+    fi
+}
 
 H_FUN='
 function human(x) {
@@ -28,207 +116,85 @@ function human_time(t) {
     return sprintf("%s%s%.1fs", h, m, s)
 }'
 
-help() {
-    orig=$(echo "$cmd" | head -n1)
-    echo "Usage: ${orig}-p [OPTION]... SOURCE DEST"
-    echo "Like ${orig} but with progress information."
-    echo
-    echo "  -F FILE    read source paths from FILE"
-    echo "  --new-line show every progress step in a new line"
-    echo "  --lf-paste to be used for lf file manager."
-    echo "             Add 'cmd paste \$cp-p --lf-paste \$id' to"
-    echo "             ~/.config/lf/lfrc"
-    echo "  --help     display this help and exit"
-    echo
-    echo "Check ${orig} --help for more options."
+main()
+{
+    printf "${B}Calculating size...${R}"
 
-    exit 1
-}
+    # total size of all sources
+    total_size=0
 
-main() {
-    if [ "$1" = '--lf-paste' ]; then
-        shift
-        lf_paste "$@"
-        return
-    fi
+    # associative array to keep the size of each source separately
+    declare -A src_sizes
 
-    if [ "$1" = --mv ]; then
-        cmd='mv'
-        shift
-    else
-        cmd='cp
--r'
-    fi
-
-    if [ "$1" = --help ]; then
-        help
-    fi
-
-    if [ "$1" = --new-line ]; then
-        R='\n'
-        B=''
-        W=99999999
-        shift
-    else
-        R=''
-        B='\033[0E\033[K'
-        W=$(tput cols)
-    fi
-
-    # ARGS STUFF
-
-    srcs=''
-    srcF=''
-    dest=''
-    opts=''
-
-    i=1
-    while [ $i -le $# ]; do
-        arg=$(eval echo '$'$i)
-        if [ $i = $# ] && [ ! "$dest" ]; then
-            dest="$arg"
-            break
+    for src in "${srcs[@]}"; do
+        if [ ! -e "$src" ]; then
+            echo "$cmd: cannot stat 'foo': No such file or directory" >&2
+            exit 1
         fi
-        if [ -e "$arg" ]; then
-            srcs="$srcs$arg
-"
-        elif [ "$arg" = '-t' ]; then
-            i=$((i + 1))
-            dest=$(eval echo '$'$i)
-        elif [ "$arg" = '-F' ]; then
-            ##### -F: file including sources files #####
-            i=$((i + 1))
-            srcF=$(eval echo '$'$i)
-        else
-            opts="$opts$arg
-"
+        src_sizes["$src"]=$(du -sb -- "$src" | awk '{print $1}')
+        if [ -n "${src_sizes["$src"]}" ]; then
+            total_size=$((total_size + ${src_sizes["$src"]}))
         fi
-        i=$((i + 1))
     done
 
-    if [ "$srcF" ]; then
-        while read -r line; do
-            if [ -e "$line" ]; then
-                srcs="$srcs$line
-"
-            fi
-        done < "$srcF"
-    fi
-
-    # remove last empty line
-    srcs=$(echo "$srcs" | head -c -1)
-
-    if [ ! "$srcs" ] || [ ! "$dest" ]; then
-        help
-    fi
-
-    # THE ACTUAL THING
-
-    printf $B'Calculating size...'$R
-
-    exists=0
-    total_size=0
-    IFS='
-'; for src in $srcs; do
-       exists=1
-       arg_size=$(du -sb "$src" 2>/dev/null | awk '{print $1}')
-       if [ -n "$arg_size" ]; then
-           total_size=$((total_size + arg_size))
-       fi
-   done
-
-    if [ "$exists" = "0" ]; then
-        echo "ERROR: No source file specified exists. Please try again"
-        exit 1
-    fi
-
+    # human-readable total size
     total_size_h=$(echo $total_size | awk "$H_FUN"'{print human($1)}')
 
 
     if [ "$cmd" = mv ]; then
-        printf $B'Moving...'$R
+        printf "${B}Moving...${R}"
     else
-        printf $B'Copying...'$R
+        printf "${B}Copying...${R}"
+        # set default options
+        opts="--archive --reflink=auto $opts"
     fi
 
-    count=0
-    IFS='
-'; for src in $srcs; do
+    # incremental size of the sources that have been copied/moved
+    incremental_size=0
 
-       # if same name
-       fname=$(basename "$src")
-       finaldest=$(realpath "$dest")
-       if [ -e "$dest/$fname" ]; then
-           copy_n=
-           # keep looping till a new name is found
-           while :; do
-               finaldest="$dest/$fname"
-               finaldest=$(echo "$finaldest" |
-                               sed -En "s/(.+)\.(.+)/\1-copy$copy_n.\2/p")
-               [ "$finaldest" ] || finaldest="$dest/$fname-copy$copy_n"
-               if [ ! -e "$finaldest" ]; then
-                   break
-               elif [ ! "$copy_n" ]; then
-                   copy_n=1
-               else
-                   copy_n=$((copy_n + 1))
-               fi
-           done
-       fi
+    for src in "${srcs[@]}"; do
+        fname=$(basename -- "$src")
+        finaldest=$(realpath -- "$dest")
 
-       strace -q -ewrite $cmd $opts "$src" "$finaldest" 2>&1 |
-           awk "$H_FUN"'
-        BEGIN { time_start = systime() }
-        {
-            time_elapsed = systime() - time_start
-            count += $NF
-            if (time_elapsed == 0 || count == 0) {
-                bytes_per_sec = -1
-                eta = -1
-            } else {
-                bytes_per_sec = count / time_elapsed
-                eta = (total_size - count) / bytes_per_sec
+        # check existing file
+        if [ -e "$dest/$fname" ]; then
+            copy_n=0
+            finaldest="$dest/$fname"
+            # keep looping till a new name is found
+            while [ -w "$finaldest" ]; do
+                copy_n=$((copy_n+1))
+                finaldest="$dest/$fname.~$copy_n~"
+            done
+        fi
+
+        strace -q -e write,copy_file_range -o >(
+            awk "$H_FUN"'
+            BEGIN { time_start = systime() }
+            {
+                time_elapsed = systime() - time_start
+                incremental_size += $NF
+                if (time_elapsed == 0 || incremental_size == 0) {
+                    bytes_per_sec = -1
+                    eta = -1
+                } else {
+                    bytes_per_sec = incremental_size / time_elapsed
+                    eta = (total_size - incremental_size) / bytes_per_sec
+                }
+                if (total_size > 0 && incremental_size % 10 == 0) {
+                    percent = (incremental_size / total_size) * 100
+                    printf "'$B'"substr(sprintf("%3d%% (%s/%s, %s/s, ETA: %s) %s to %s'$R'", percent, human(incremental_size), total_size_h, human(bytes_per_sec), human_time(eta), src, finaldest), 0, '$W')
+                }
             }
-            if (total_size > 0 && count % 10 == 0) {
-                percent = (count / total_size) * 100
-                printf "'$B'"substr(sprintf("%3d%% (%s/%s, %s/s, ETA: %s) %s to %s'$R'", percent, human(count), total_size_h, human(bytes_per_sec), human_time(eta), src, finaldest), 0, '$W')
-            }
-        }
-        END { print "'$B'Took " human_time(systime() - time_start) }' \
-               total_size=$total_size \
-               total_size_h="$total_size_h" \
-               count=$count \
-               src="$src" finaldest="$finaldest"
+            END { print "'$B'Took " human_time(systime() - time_start) }' \
+                total_size=$total_size \
+                total_size_h="$total_size_h" \
+                incremental_size=$incremental_size \
+                src="$src" finaldest="$finaldest"
+            ) $cmd $opts -- "$src" "$finaldest"
 
-       arg_size=$(du -sb "$src" 2>/dev/null | awk '{ print $1 }')
-       count=$((count + arg_size))
-   done
-
-    if [ "$cmd" = mv ]; then
-        echo 'Done moving'
-    else
-        echo 'Done copying'
-    fi
-
+        incremental_size=$((incremental_size + ${src_sizes["$src"]}))
+    done
 }
 
-# to be used only for `lf` file manager. cp-p and mv-p must be on $PATH
-lf_paste() {
-    id="$1"
-    send="while read -r line; do lf -remote \"send $id echo \$line\"; done && lf -remote 'send reload'"
-    load=$(cat ~/.local/share/lf/files)
-    mode=$(echo "$load" | sed -n '1p')
-    srcF=$(mktemp)
-    echo "$load" | sed '1d' > "$srcF"
-    s='' && [ ! -w . ] && s='sudo'
-    case "$mode" in
-        copy) cmd='cp-p';; move) cmd='mv-p';;
-    esac
-    cmd="$cmd --new-line"
-    [ "$mode" = copy ] && cmd="$cmd -a"
-    sh -c "$s $cmd --backup=numbered -F \"$srcF\" . | $send && rm -f \"$srcF\" &"
-    rm ~/.local/share/lf/files
-    lf -remote 'send clear'
-}
-
-main "$@"
+parse_command_line "$@"
+main
